name: gmodawebmotor
description: The Flutter's test to Webmotor.
version: 1.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


dartfmt:
  line_length: 120

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter         

  # https://pub.dev/packages/intl/
  intl: ^0.17.0


  # https://pub.dev/packages/cupertino_icons/
  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/get_it/
  get_it: ^7.2.0

  # https://pub.dev/packages/injectable/
  injectable: ^1.5.3

  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.4.0

  # https://pub.dev/packages/json_serializable/install
  json_serializable: ^6.1.5

  # https://pub.dev/packages/go_router/
  go_router: ^3.0.4

  # https://pub.dev/packages/retrofit/
  retrofit: ^3.0.1+1

  # https://pub.dev/packages/dio/
  dio: ^4.0.4

  # https://pub.dev/packages/freezed_annotation/
  freezed_annotation: ^1.1.0

  # https://pub.dev/packages/uuid/
  uuid: ^3.0.6

  # https://pub.dev/packages/logger/
  logger: ^1.1.0

  # https://pub.dev/packages/flutter_mobx/
  flutter_mobx: ^2.0.4

  # https://pub.dev/packages/cached_network_image/
  cached_network_image: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints/
  flutter_lints: ^1.0.0

  # https://pub.dev/packages/build_runner/
  build_runner: ^2.1.8

  # https://pub.dev/packages/injectable_generator/
  injectable_generator: ^1.5.3

  # https://pub.dev/packages/retrofit_generator/
  retrofit_generator: ^4.0.1

  # https://pub.dev/packages/faker/
  faker: ^2.0.0

  # https://pub.dev/packages/freezed/
  freezed: ^1.1.1

  # https://pub.dev/packages/mockito/
  mockito: ^5.1.0

  # https://pub.dev/packages/http_mock_adapter/
  http_mock_adapter: ^0.3.2

  # https://pub.dev/packages/mobx_codegen/
  mobx_codegen: ^2.0.5+2
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/logo.png

