name: gmodawebmotor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # https://pub.dev/packages/cupertino_icons/
  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/get_it/
  get_it: ^7.2.0

  # https://pub.dev/packages/injectable/
  injectable: ^1.5.3

  # https://pub.dev/packages/get_it/
  go_router: ^3.0.4

  # https://pub.dev/packages/retrofit/
  retrofit: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints/
  flutter_lints: ^1.0.0

  # https://pub.dev/packages/build_runner/
  build_runner: ^2.1.8

  # https://pub.dev/packages/injectable_generator/
  injectable_generator: ^1.5.3

  # https://pub.dev/packages/retrofit_generator/
  retrofit_generator: ^4.0.1

  # https://pub.dev/packages/json_serializable/
  json_serializable: ^6.1.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 
